Repository SU-SOE/soe_profile, pull requests merged in 2020-10, with the labels that each got.

#77 Disabled external links
  config/sync/extlink.settings.yml
  tests/codeception/functional/Contrib/ExtLinkCest.php
Labels: size/xs

#78 Removed double header on person
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  tests/codeception/acceptance/Content/PersonCest.php
Labels: size/xs

#79 8.1.3
  CHANGELOG.md
  composer.json
  config/sync/extlink.settings.yml
  soe_profile.info.yml
Labels: patch, size/xs

#80 D8CORE-2548: fixing the load more button to 20 from 10
  config/sync/views.view.stanford_news.yml
Labels: size/xs

#81 8.1.4
  CHANGELOG.md
  config/sync/views.view.stanford_news.yml
  soe_profile.info.yml
  tests/codeception/acceptance/Content/PersonCest.php
Labels: patch, size/xs

#82 SOEOP-339: Created `site_embedder` role.
  composer.json
  config/sync/core.extension.yml
  config/sync/core.menu.static_menu_link_overrides.yml
  config/sync/migrate_plus.migration.su_stanford_person.yml
  config/sync/system.action.user_add_role_action.soe_site_embedder.yml
  config/sync/system.action.user_remove_role_action.soe_site_embedder.yml
  config/sync/user.role.soe_site_embedder.yml
  config/sync/views.view.stanford_news.yml
  config/sync/views.view.stanford_person.yml
  tests/codeception/acceptance/Media/MediaPermissionsCest.php
  tests/codeception/acceptance/Users/RolesCest.php
Labels: size/s
