Repository SU-SOE/soe_profile, pull requests merged in 2020-06, with the labels that each got.

#39 D8CORE-2149: Updated tests and sync with stanford_profile.
  .circleci/config.yml
  composer.json
  config/sync/ultimate_cron.job.stanford_migrate_stanford_events_importer.yml
  config/sync/views.view.stanford_news.yml
  tests/behat/assets/documents/test.php
  tests/behat/features/BasicPage.feature
  tests/behat/features/DefaultContent.feature
  tests/behat/features/LocalFooter.feature
  tests/behat/features/Paragraphs/Banner.feature
  tests/behat/features/Paragraphs/Issue2901390.feature
  tests/behat/features/Paragraphs/MediaWithCaption.feature
  tests/behat/features/Paragraphs/WYSIWYG.feature
  tests/behat/features/SystemSiteConfig.feature
  tests/behat/features/TextFormats.feature
  tests/behat/features/Users/DefaultUsers.feature
  tests/behat/features/Users/Roles.feature
  tests/behat/features/contrib/config_readonly.feature
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/DefaultContentCest.php
  tests/codeception/acceptance/Contrib/ConfigReadonlyCest.php
  tests/codeception/acceptance/LocalFooterCest.php
  tests/codeception/acceptance/Paragraphs/BannerCest.php
  tests/codeception/acceptance/Paragraphs/Issue2901390Cest.php
  tests/codeception/acceptance/Paragraphs/MediaWithCaptionCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/acceptance/TextFormatsCest.php
  tests/codeception/acceptance/Users/DefaultUsersCest.php
  tests/codeception/acceptance/Users/RolesCest.php
  tests/codeception/functional/Paragraphs/WYSIWYG.html
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
  tests/codeception/functional/Paragraphs/logo.jpg
  tests/codeception/functional/Paragraphs/test.txt
Labels: size/l

#40 SOE basic theme.
  config/sync/block.block.config_pages_2.yml
  config/sync/block.block.soe_basic_branding.yml
  config/sync/block.block.soe_basic_content.yml
  config/sync/block.block.soe_basic_help.yml
  config/sync/block.block.soe_basic_local_tasks.yml
  config/sync/block.block.soe_basic_main_navigation.yml
  config/sync/block.block.soe_basic_messages.yml
  config/sync/block.block.soe_basic_pagetitle.yml
  config/sync/block.block.soe_basic_search.yml
  config/sync/system.theme.yml
Labels: size/s

#42 D8CORE-000: remove xmlsitemap patch, bump to 1.0.0, lose the alpha.
  composer.json
Labels: size/xs
