Repository SU-SOE/soe_profile, pull requests merged in 2020-08, with the labels that each got.

#61 D8CORE-2453: Missing changes from diff.
  config/sync/config_ignore.settings.yml
  config/sync/config_pages.type.stanford_basic_site_settings.yml
  config/sync/config_pages.type.stanford_events_importer.yml
  config/sync/config_pages.type.stanford_local_footer.yml
  config/sync/config_pages.type.stanford_person_importer.yml
  config/sync/config_pages.type.stanford_saml.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/stanford_basic.settings.yml
  config/sync/views.view.content.yml
  soe_profile.info.yml
  src/Config/ConfigOverrides.php
  src/Plugin/HelpSection/ProfileHelpSection.php
  src/Plugin/HelpSection/ProfileResourceSection.php
  tests/codeception/acceptance/Contrib/NodeRevisionDeleteCest.php
  tests/src/Unit/Config/ConfigOverridesTest.php
  tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
Labels: patch, size/s

#62 DEVOPS-000: removed field formatter patch again.
  composer.json
Labels: patch, size/xs

#63 DEVOPS-000: Update paragraphs lang patch
  composer.json
Labels: size/xs
