Repository SU-SOE/soe_profile, pull requests merged in 2020-07, with the labels that each got.

#43 D8CORE-2129: configs for updates in the SOE paragraphs.
  config/sync/core.entity_view_display.paragraph.stanford_image_cta.default.yml
  config/sync/field.storage.paragraph.stanford_stories_border.yml
Labels: size/xs

#47 D8CORE-2273: added tests for cta list and image cta
  tests/codeception/acceptance/Paragraphs/StanfordCTAListCest.php
  tests/codeception/acceptance/Paragraphs/StanfordImageCTACest.php
  tests/codeception/acceptance/Paragraphs/StanfordStoriesCest.php
Labels: size/s

#44 D8CORE-2317: changes for the location
  config/sync/views.view.stanford_event_series.yml
  config/sync/views.view.stanford_events.yml
Labels: size/l

#49 Update composer.json
  composer.json
Labels: size/xs

#52 D8CORE-2249: try again with exporting
  config/sync/page_manager.page_variant.event_series-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_list-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_past-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_upcoming-layout_builder-0.yml
Labels: size/xs

#54 D8CORE-2252: Person config changes.
  config/sync/core.entity_view_display.node.stanford_event_series.default.yml
  config/sync/page_manager.page_variant.people-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_news_list-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_news_list_terms-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_person_list-layout_builder-0.yml
Labels: size/xs

#56 D8CORE-2298: moved the h1 above the hero banner image
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/layout_library.layout.stanford_basic_page_full.yml
Labels: size/xs

#58 D8CORE-2132: Fixing the event node header
  config/sync/core.entity_view_display.node.stanford_event.default.yml
Labels: size/xs
