Repository SU-SOE/soe_profile, pull requests merged in 2021-04, with the labels that each got.

#127 Updates from stanford_profile
  config/sync/core.entity_form_display.citation.su_other.default.yml
  config/sync/core.entity_view_display.citation.su_other.default.yml
  config/sync/field.field.citation.su_other.su_author.yml
  config/sync/field.field.citation.su_other.su_day.yml
  config/sync/field.field.citation.su_other.su_month.yml
  config/sync/field.field.citation.su_other.su_publisher.yml
  config/sync/field.field.citation.su_other.su_subtitle.yml
  config/sync/field.field.citation.su_other.su_url.yml
  config/sync/field.field.citation.su_other.su_year.yml
  config/sync/field.field.node.stanford_publication.su_publication_citation.yml
  config/sync/stanford_publication.citation_type.su_other.yml
  config/sync/views.view.stanford_person_list_terms_first.yml
  config/sync/views.view.stanford_publications.yml
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/Content/PublicationsCest.php
  tests/codeception/acceptance/HomePageCest.php
Labels: size/m

#130 Updates from stanford_profile
  config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
Labels: size/xs

#131 Updates from stanford_profile
  config/sync/config_pages.type.stanford_saml.yml
  config/sync/field.field.config_pages.stanford_global_message.su_global_msg_message.yml
  config/sync/stanford_ssp.settings.yml
  config/sync/views.view.stanford_events.yml
Labels: size/xs

#132 Updates from stanford_profile
  config/sync/content_lock.settings.yml
  config/sync/content_lock_timeout.settings.yml
  config/sync/core.entity_view_display.node.stanford_publication.teaser.yml
  config/sync/core.extension.yml
  config/sync/system.action.media_break_lock_action.yml
  config/sync/system.action.node_break_lock_action.yml
  config/sync/ultimate_cron.job.content_lock_timeout_cron.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.locked_content.yml
Labels: size/m

#136 Updates from Stanford Profile 2021-04-11
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_form_display.taxonomy_term.event_audience.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/core.entity_view_display.node.stanford_event_series.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event_series.teaser.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_page.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_person.teaser.yml
  config/sync/core.entity_view_display.node.stanford_publication.teaser.yml
  config/sync/core.entity_view_display.paragraph.stanford_banner.variant_1.yml
  config/sync/core.extension.yml
  config/sync/ds.field.basic_page_type_content_url.yml
  config/sync/field.field.config_pages.stanford_global_message.su_global_msg_message.yml
  config/sync/field.field.node.stanford_page.su_basic_page_type.yml
  config/sync/field.field.node.stanford_page.su_page_description.yml
  config/sync/field.field.node.stanford_page.su_page_image.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  config/sync/field.storage.node.su_basic_page_type.yml
  config/sync/field.storage.node.su_page_description.yml
  config/sync/field.storage.node.su_page_image.yml
  config/sync/metatag.metatag_defaults.node.yml
  config/sync/migrate_plus.migration.su_stanford_person.yml
  config/sync/taxonomy.vocabulary.basic_page_types.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.stanford_basic_pages.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
Labels: size/l

#141 8.2.5
  CHANGELOG.md
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/node.type.stanford_publication.yml
  config/sync/views.view.stanford_basic_pages.yml
  soe_profile.info.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
Labels: patch, size/xs

#143 8.2.6
  CHANGELOG.md
  config/sync/field.field.citation.su_article_journal.su_author.yml
  config/sync/field.field.citation.su_article_newspaper.su_author.yml
  config/sync/field.field.citation.su_book.su_author.yml
  config/sync/field.field.citation.su_other.su_author.yml
  config/sync/field.field.citation.su_thesis.su_author.yml
  config/sync/field.field.node.stanford_page.su_basic_page_type.yml
  config/sync/views.view.stanford_basic_pages.yml
  soe_profile.info.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/PublicationsCest.php
Labels: patch, size/xs

#144 8.2.7
  CHANGELOG.md
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/taxonomy.vocabulary.basic_page_types.yml
  soe_profile.info.yml
Labels: patch, size/xs

#145 D8CORE-2808: changing the help text to say below the page title
  config/sync/field.field.node.stanford_page.su_page_banner.yml
Labels: size/xs
