Repository SU-SOE/soe_profile, pull requests merged in 2021-09, with the labels that each got.

#182 Updates from stanford_profile
  config/sync/page_manager.page_variant.people-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_list-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_upcoming-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_news_list-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_news_list_terms-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_person_list-layout_builder-0.yml
Labels: size/s

#184 8.2.12
  CHANGELOG.md
  config/sync/core.entity_form_display.paragraph.stanford_accordion.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_accordion.default.yml
  config/sync/core.extension.yml
  config/sync/editoria11y.settings.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_google_analytics.yml
  config/sync/field.field.node.stanford_event.su_event_components.yml
  config/sync/field.field.node.stanford_event.su_event_email.yml
  config/sync/field.field.node.stanford_event.su_event_map_link.yml
  config/sync/field.field.node.stanford_event.su_event_schedule.yml
  config/sync/field.field.node.stanford_event.su_event_telephone.yml
  config/sync/field.field.node.stanford_event_series.su_event_series_components.yml
  config/sync/field.field.node.stanford_event_series.su_event_series_event.yml
  config/sync/field.field.node.stanford_event_series.su_event_series_subheadline.yml
  config/sync/field.field.node.stanford_event_series.su_event_series_type.yml
  config/sync/field.field.paragraph.stanford_accordion.su_accordion_body.yml
  config/sync/field.field.paragraph.stanford_accordion.su_accordion_title.yml
  config/sync/field.field.paragraph.stanford_person_cta.su_person_cta_link.yml
  config/sync/field.field.paragraph.stanford_person_cta.su_person_cta_name.yml
  config/sync/field.field.paragraph.stanford_person_cta.su_person_cta_title.yml
  config/sync/field.storage.paragraph.su_accordion_body.yml
  config/sync/field.storage.paragraph.su_accordion_title.yml
  config/sync/field_validation.rule_set.config_pages_stanford_basic_site_settings.yml
  config/sync/page_manager.page_variant.people-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_list-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_upcoming-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_news_list-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_news_list_terms-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_person_list-layout_builder-0.yml
  config/sync/paragraphs.paragraphs_type.stanford_accordion.yml
  config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_stanford_event_types.yml
  config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_stanford_news_topics.yml
  config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_stanford_person_types.yml
  config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_stanford_publication_topics.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.stanford_publications.yml
  soe_profile.info.yml
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Content/PublicationsCest.php
  tests/codeception/acceptance/Users/RolesCest.php
  tests/codeception/functional/Paragraphs/AccordionCest.php
Labels: patch, size/m

#185 Updates from stanford_profile
  config/sync/field.field.node.stanford_event.su_event_components.yml
  config/sync/field.field.node.stanford_news.su_news_components.yml
  config/sync/field.field.node.stanford_person.su_person_components.yml
  config/sync/field.field.paragraph_row.node_stanford_page_row.su_page_components.yml
  tests/codeception/functional/Paragraphs/AccordionCest.php
Labels: size/xs

#186 8.2.13
  CHANGELOG.md
  config/sync/field.field.node.stanford_event.su_event_components.yml
  config/sync/field.field.node.stanford_news.su_news_components.yml
  config/sync/field.field.node.stanford_person.su_person_components.yml
  config/sync/field.field.paragraph_row.node_stanford_page_row.su_page_components.yml
  soe_profile.info.yml
  tests/codeception/functional/Paragraphs/AccordionCest.php
Labels: size/xs, patch

#189 8.2.14
  CHANGELOG.md
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
Labels: size/xs, patch

#190 Updates from stanford_profile
  config/sync/field.field.media.embeddable.field_media_embeddable_code.yml
  config/sync/media.type.embeddable.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  tests/codeception/acceptance/Media/MediaPermissionsCest.php
Labels: size/xs

#191 Updates from stanford_profile
  config/sync/system.action.user_add_role_action.layout_builder_user.yml
  config/sync/system.action.user_remove_role_action.layout_builder_user.yml
  config/sync/user.role.layout_builder_user.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_manager.yml
  tests/codeception/acceptance/Paragraphs/Issue2901390Cest.php
Labels: size/xs

#192 Updates from stanford_profile
  config/sync/core.extension.yml
  config/sync/stanford_actions.settings.yml
  config/sync/views.view.content.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/acceptance/Content/PersonCest.php
Labels: size/s

#193 Updates from stanford_profile
  config/sync/core.entity_view_display.node.stanford_event.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_event_series.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.node.stanford_news.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_page.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_person.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.search_indexing.yml
  config/sync/core.entity_view_mode.node.search_indexing.yml
  config/sync/search_api.index.full_site_content.yml
  src/Plugin/HelpSection/ProfileConnectSection.php
  src/Plugin/HelpSection/ProfileHelpSection.php
  src/Plugin/HelpSection/ProfileResourceSection.php
  tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
Labels: size/l

#194 Updates from stanford_profile
  config/sync/admin_toolbar.settings.yml
  config/sync/core.entity_form_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_publication.teaser.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.stanford_publication.su_publication_image.yml
  config/sync/field.storage.node.su_publication_image.yml
  config/sync/migrate_plus.migration.stanford_publications.yml
  config/sync/views.view.stanford_events.yml
Labels: size/s

#195 Updates from stanford_profile
  config/sync/migrate_plus.migration.stanford_publications.yml
  config/sync/user.role.site_manager.yml
Labels: size/xs
