Repository SU-SOE/soe_profile, pull requests merged in 2021-05, with the labels that each got.

#151 Updates from stanford_profile
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_schedule.default.yml
  config/sync/field.field.citation.su_article_journal.su_author.yml
  config/sync/field.field.citation.su_article_newspaper.su_author.yml
  config/sync/field.field.citation.su_book.su_author.yml
  config/sync/field.field.citation.su_other.su_author.yml
  config/sync/field.field.citation.su_thesis.su_author.yml
  config/sync/field.field.node.stanford_event.su_event_alt_loc.yml
  config/sync/field.field.node.stanford_news.su_news_topics.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  config/sync/paragraphs.paragraphs_type.stanford_banner.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  tests/codeception/functional/Paragraphs/BannerCest.php
Labels: size/s

#154 Updates from stanford_profile
  config/sync/core.entity_view_display.node.stanford_event_series.stanford_card.yml
  config/sync/core.entity_view_display.paragraph.stanford_lists.default.yml
  config/sync/views.view.stanford_publications.yml
  config/sync/views.view.user_search.yml
Labels: size/m

#160 Updates from stanford_profile
  config/sync/colorbox.settings.yml
  config/sync/core.extension.yml
  config/sync/views.view.user_admin_people.yml
  tests/codeception/acceptance/AuthenticatedPermissionsCest.php
  tests/codeception/acceptance/Users/DefaultUsersCest.php
  tests/codeception/acceptance/Users/RolesCest.php
Labels: size/xs

#161 8.2.8
  CHANGELOG.md
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_schedule.default.yml
  config/sync/core.entity_view_display.node.stanford_event_series.stanford_card.yml
  config/sync/core.entity_view_display.paragraph.stanford_lists.default.yml
  config/sync/field.field.citation.su_article_journal.su_author.yml
  config/sync/field.field.citation.su_article_newspaper.su_author.yml
  config/sync/field.field.citation.su_book.su_author.yml
  config/sync/field.field.citation.su_other.su_author.yml
  config/sync/field.field.citation.su_thesis.su_author.yml
  config/sync/field.field.node.stanford_event.su_event_alt_loc.yml
  config/sync/field.field.node.stanford_news.su_news_topics.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  config/sync/paragraphs.paragraphs_type.stanford_banner.yml
  config/sync/stanford_ssp.settings.yml
  config/sync/ultimate_cron.job.stanford_fields_cron.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.stanford_publications.yml
  config/sync/views.view.user_admin_people.yml
  tests/codeception/functional/Paragraphs/BannerCest.php
Labels: patch, size/l

#162 8.2.9
  CHANGELOG.md
  config/sync/core.entity_view_display.paragraph.stanford_cta_list.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_image_cta.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_stories.default.yml
  config/sync/extlink.settings.yml
  config/sync/page_manager.page_variant.event_series-layout_builder-0.yml
  config/sync/page_manager.page_variant.people-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_list-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_past-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_events_upcoming-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_news_list-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_news_list_terms-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_person_list-layout_builder-0.yml
  config/sync/paragraphs.paragraphs_type.stanford_banner.yml
  soe_profile.info.yml
  tests/codeception/functional/Paragraphs/BannerCest.php
Labels: patch, size/xs

#164 Updates from stanford_profile
  config/sync/config_pages.type.stanford_saml.yml
  config/sync/core.entity_form_display.config_pages.stanford_saml.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_saml.default.yml
  config/sync/field.field.config_pages.stanford_saml.su_simplesaml_affil.yml
  config/sync/field.storage.config_pages.su_simplesaml_affil.yml
  config/sync/stanford_ssp.settings.yml
Labels: size/xs
