Repository SU-SOE/soe_profile, pull requests merged in 2021-03, with the labels that each got.

#103 D8CORE-3563 Limit the image gallery to one per row
  config/sync/block.block.soe_basic_config_pages_stanford_global_msg.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
Labels: size/xs

#107 Updates from stanford_profile
  config/sync/block.block.stanford_basic_pagetitle.yml
  config/sync/core.entity_view_display.citation.su_thesis.default.yml
  config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.citation.su_thesis.su_publisher.yml
  config/sync/field.field.citation.su_thesis.su_year.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  config/sync/system.menu.stanford-publication-topics.yml
  config/sync/taxonomy_menu.taxonomy_menu.publication_topics.yml
  config/sync/views.view.publication_terms.yml
  config/sync/views.view.stanford_events.yml
  config/sync/views.view.stanford_news.yml
  config/sync/views.view.stanford_person.yml
  config/sync/views.view.stanford_publications.yml
  content/node/ce9cb7ca-6c59-4eea-9934-0a33057a7ff2.yml
  content/paragraph/9939d5e0-a261-4f99-b08a-9ba5b43908c1.yml
  content/paragraph_row/e9158340-cb5c-494e-9c66-a959208fe4a8.yml
  tests/codeception/acceptance/Content/PublicationsCest.php
  tests/codeception/functional/Contrib/RedirectImportCest.php
Labels: size/l

#109 Updates from stanford_profile
  config/sync/admin_toolbar_tools.settings.yml
Labels: size/xs

#108 D8CORE-3247: updates for the background header colors
  config/sync/block.block.soe_basic_pagetitle.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
Labels: size/xs

#110 Updates from stanford_profile
  config/sync/views.view.publication_terms.yml
Labels: size/xs

#113 Updates from stanford_profile
  config/sync/core.entity_form_display.config_pages.stanford_person_importer.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_person_importer.default.yml
  config/sync/field.field.config_pages.stanford_person_importer.su_person_child_orgs.yml
  config/sync/field.storage.config_pages.su_person_child_orgs.yml
Labels: size/xs

#118 Updates from stanford_profile
  CHANGELOG.md
  composer.json
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/field.field.paragraph_row.su_pub_rows.su_pubs_components.yml
  config/sync/views.view.publication_terms.yml
  config/sync/views.view.stanford_publications.yml
  soe_profile.info.yml
Labels: patch, size/xs

#119 8.2.3
  CHANGELOG.md
  config/sync/views.view.stanford_publications.yml
  soe_profile.info.yml
Labels: patch, size/xs

#120 Updates from stanford_profile
  config/sync/config_ignore.settings.yml
  config/sync/config_pages.type.stanford_saml.yml
  config/sync/core.entity_form_display.config_pages.stanford_saml.default.yml
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.node.stanford_event_series.default.yml
  config/sync/core.entity_form_display.node.stanford_news.default.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_form_display.node.stanford_person.default.yml
  config/sync/core.entity_form_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_saml.default.yml
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event.teaser.yml
  config/sync/core.entity_view_display.node.stanford_event_series.default.yml
  config/sync/core.entity_view_display.node.stanford_event_series.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event_series.teaser.yml
  config/sync/core.entity_view_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_page.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_person.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_person.teaser.yml
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.teaser.yml
  config/sync/core.extension.yml
  config/sync/field.field.config_pages.stanford_saml.su_simplesaml_allowed.yml
  config/sync/field.field.config_pages.stanford_saml.su_simplesaml_users.yml
  config/sync/field.field.node.stanford_event.stanford_intranet__access.yml
  config/sync/field.field.node.stanford_event_series.stanford_intranet__access.yml
  config/sync/field.field.node.stanford_news.stanford_intranet__access.yml
  config/sync/field.field.node.stanford_page.stanford_intranet__access.yml
  config/sync/field.field.node.stanford_person.stanford_intranet__access.yml
  config/sync/field.field.node.stanford_publication.stanford_intranet__access.yml
  config/sync/field.storage.config_pages.su_simplesaml_allowed.yml
  config/sync/field.storage.config_pages.su_simplesaml_users.yml
  config/sync/field.storage.node.stanford_intranet__access.yml
  config/sync/user.role.site_manager.yml
  tests/codeception/acceptance/Users/IntranetCest.php
Labels: size/m

#121 Updates from stanford_profile
  config/sync/views.view.publication_terms.yml
Labels: size/xs

#125 Updates from stanford_profile
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
Labels: size/s

#126 Updates from stanford_profile
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
Labels: size/xs
