Repository SU-SOE/soe_profile, pull requests merged in 2022-03, with the labels that each got.

#226 Updates from stanford_profile
  config/sync/core.extension.yml
  tests/codeception/acceptance/SubThemeCest.php
Labels: size/xs

#227 Updates from stanford_profile
  config/sync/core.entity_form_display.taxonomy_term.cap_org_codes.default.yml
  config/sync/core.entity_form_display.taxonomy_term.event_audience.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.extension.yml
  config/sync/webp.settings.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
Labels: size/xs

#228 Updates from stanford_profile
  config/sync/core.entity_form_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_form_display.config_pages.stanford_local_footer.default.yml
  config/sync/core.entity_view_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_local_footer.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.config_pages.lockup_settings.su_intro.yml
  config/sync/field.field.config_pages.stanford_local_footer.su_local_foot_help.yml
  config/sync/field.storage.config_pages.su_intro.yml
  config/sync/field.storage.config_pages.su_local_foot_help.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/ultimate_cron.job.core_event_dispatcher_cron.yml
Labels: size/m

#229 Updates from stanford_profile
  config/sync/core.entity_form_display.media.embeddable.default.yml
  config/sync/core.entity_form_display.media.embeddable.media_library.yml
  config/sync/core.entity_form_display.media.file.default.yml
  config/sync/core.entity_form_display.media.file.media_library.yml
  config/sync/core.entity_form_display.media.google_form.default.yml
  config/sync/core.entity_form_display.media.google_form.media_library.yml
  config/sync/core.entity_form_display.media.image.default.yml
  config/sync/core.entity_form_display.media.image.media_library.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.default.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_form_display.media.video.default.yml
  config/sync/core.entity_form_display.media.video.media_library.yml
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.node.stanford_event_series.default.yml
  config/sync/core.entity_form_display.node.stanford_news.default.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_form_display.node.stanford_person.default.yml
  config/sync/core.entity_form_display.node.stanford_publication.default.yml
  config/sync/core.entity_form_display.taxonomy_term.cap_org_codes.default.yml
  config/sync/core.entity_form_display.taxonomy_term.event_audience.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_publication_topics.default.yml
Labels: size/s

#230 Updates from stanford_profile
  config/sync/core.extension.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/google_analytics.settings.yml
  config/sync/jsonapi.settings.yml
  config/sync/jsonapi_extras.settings.yml
  config/sync/layout_library.layout.stanford_basic_page_full.yml
  config/sync/migrate_plus.migration.stanford_localist_importer.yml
  config/sync/pathauto.pattern.event_nodes.yml
  config/sync/pathauto.pattern.event_types.yml
  config/sync/pathauto.pattern.news_topics.yml
  config/sync/pathauto.pattern.person.yml
  config/sync/pathauto.pattern.stanford_publication_topics.yml
  config/sync/pathauto.pattern.stanford_publications.yml
  config/sync/views.view.stanford_person_list_terms_first.yml
  tests/codeception/acceptance/Content/PersonCest.php
Labels: size/s

#234 8.3.1
  CHANGELOG.md
  composer.json
  config/sync/core.entity_form_display.config_pages.stanford_events_importer.default.yml
  config/sync/field.field.config_pages.lockup_settings.su_lockup_options.yml
  config/sync/node.type.stanford_event.yml
  soe_profile.info.yml
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Media/MediaPermissionsCest.php
Labels: patch
