Repository SU-SOE/soe_profile, pull requests merged in 2022-01, with the labels that each got.

#209 Updates from stanford_profile
  config/sync/block.block.soe_basic_search.yml
  config/sync/block.block.stanford_basic_search.yml
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/extlink.settings.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_hide_site_search.yml
  config/sync/field.field.config_pages.stanford_events_importer.su_localist_url.yml
  config/sync/field.storage.config_pages.su_hide_site_search.yml
  tests/codeception/acceptance/Content/SearchBlockCest.php
Labels: size/s

#213 Updates from stanford_profile
  config/sync/migrate_plus.migration.stanford_localist_importer.yml
Labels: size/xs

#214 Updates from stanford_profile
  config/sync/block.block.config_pages.yml
  config/sync/block.block.stanford_basic_config_pages_stanford_global_msg.yml
  config/sync/block.block.stanford_basic_config_pages_stanford_super_footer.yml
  config/sync/extlink.settings.yml
  config/sync/filter.format.stanford_minimal_html.yml
  config/sync/migrate_plus.migration.stanford_localist_importer.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.publication_terms.yml
  config/sync/views.view.stanford_basic_pages.yml
  config/sync/views.view.stanford_event_series.yml
  config/sync/views.view.stanford_event_terms_utility.yml
  config/sync/views.view.stanford_events.yml
  config/sync/views.view.stanford_events_past.yml
  config/sync/views.view.stanford_events_schedule.yml
  config/sync/views.view.stanford_person_list_terms_first.yml
  config/sync/views.view.stanford_publications.yml
  config/sync/views.view.su_block_edit_links.yml
  content/file/84d7eaff-e426-446f-a462-c06e48f7e11a.yml
  content/media/434972e6-21fb-41a7-b741-97a322b2910f.yml
  soe_profile.info.yml
  tests/codeception/acceptance/Content/SearchBlockCest.php
Labels: size/s, patch

#216 Updates from stanford_profile
  config/sync/block.block.stanford_basic_search.yml
  config/sync/core.entity_form_display.config_pages.stanford_events_importer.default.yml
  config/sync/field.field.config_pages.stanford_events_importer.su_event_xml_url.yml
  config/sync/views.view.files.yml
  tests/codeception/acceptance/Content/SearchBlockCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/Media/test.pdf
Labels: size/l

#217 8.2.19
  CHANGELOG.md
  composer.json
  config/sync/block.block.soe_basic_search.yml
  soe_profile.info.yml
Labels: size/xs, patch
