Repository SU-SOE/soe_profile, pull requests merged in 2022-12, with the labels that each got.

#289 excise memcache
  composer.json
  config/sync/config_split.config_split.prod.yml
Labels: size/xs, patch

#290 hotfix-12-03-2022
  CHANGELOG.md
  composer.json
  config/sync/config_split.config_split.dev.yml
  config/sync/config_split.config_split.stage.yml
Labels: size/xs

#291 9.2.4
  CHANGELOG.md
  composer.json
  config/sync/core.entity_view_display.node.stanford_policy.default.yml
  config/sync/menu_link_weight.settings.yml
  soe_profile.info.yml
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
Labels: size/s, patch
