Repository SU-SOE/soe_profile, pull requests merged in 2022-02, with the labels that each got.

#218 Updates from stanford_profile
  config/sync/views.view.stanford_event_series.yml
  config/sync/views.view.stanford_events.yml
  config/sync/views.view.stanford_events_past.yml
  config/sync/views.view.stanford_news.yml
  config/sync/views.view.stanford_person.yml
  config/sync/views.view.stanford_person_list_terms_first.yml
  config/sync/views.view.stanford_publications.yml
Labels: size/xs

#219 Updates from stanford_profile
  config/sync/core.entity_view_display.node.stanford_event_series.default.yml
Labels: size/xs

#220 8.2.20
  CHANGELOG.md
  config/sync/core.entity_view_display.node.stanford_event_series.default.yml
  soe_profile.info.yml
Labels: size/xs, patch

#221 Updates from stanford_profile
  config/sync/core.entity_form_display.media.embeddable.default.yml
  config/sync/core.entity_form_display.media.embeddable.media_library.yml
  config/sync/core.entity_form_display.media.file.default.yml
  config/sync/core.entity_form_display.media.file.media_library.yml
  config/sync/core.entity_form_display.media.google_form.default.yml
  config/sync/core.entity_form_display.media.google_form.media_library.yml
  config/sync/core.entity_form_display.media.image.default.yml
  config/sync/core.entity_form_display.media.image.media_library.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.default.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_form_display.media.video.default.yml
  config/sync/core.entity_form_display.media.video.media_library.yml
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.node.stanford_event_series.default.yml
  config/sync/core.entity_form_display.node.stanford_news.default.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_form_display.node.stanford_person.default.yml
  config/sync/core.entity_form_display.node.stanford_publication.default.yml
  config/sync/core.extension.yml
  config/sync/node.type.stanford_event.yml
  config/sync/node.type.stanford_event_series.yml
  config/sync/node.type.stanford_news.yml
  config/sync/node.type.stanford_page.yml
  config/sync/node.type.stanford_person.yml
  config/sync/node.type.stanford_publication.yml
  config/sync/pathauto.pattern.default.yml
  config/sync/scheduler.settings.yml
  config/sync/ultimate_cron.job.scheduler_cron.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.scheduler_scheduled_content.yml
  config/sync/views.view.scheduler_scheduled_media.yml
  src/Config/ConfigOverrides.php
  tests/codeception/acceptance/Content/BasicPageCest.php
Labels: size/l

#222 Updates from stanford_profile
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/smart_date.smart_date_format.compact.yml
  config/sync/smart_date.smart_date_format.date_only.yml
  config/sync/smart_date.smart_date_format.default.yml
  config/sync/smart_date.smart_date_format.stanford_event_long_no_time.yml
  config/sync/smart_date.smart_date_format.stanford_events_long.yml
  config/sync/smart_date.smart_date_format.time_only.yml
  config/sync/smart_date.smart_date_format.time_only_no_all_day.yml
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
Labels: size/xs

#224 Updates from stanford_profile
  tests/codeception/acceptance/Users/IntranetCest.php
Labels: size/xs
