Repository SU-SOE/soe_profile, pull requests merged in 2022-05, with the labels that each got.

#251 D8CORE-5826: updating the header background images.
  config/sync/core.entity_view_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
  tests/codeception/functional/Contrib/ExtLinkCest.php
Labels: size/xs

#250 Update block.block.soe_basic_pagetitle.yml
  config/sync/block.block.soe_basic_pagetitle.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
  tests/codeception/functional/Contrib/ExtLinkCest.php
Labels: size/xs

#249 8.4.1
  CHANGELOG.md
  composer.json
  config/sync/block.block.soe_basic_pagetitle.yml
  config/sync/config_pages.type.stanford_basic_site_settings.yml
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_403.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_404.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_home.yml
  config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_caption.yml
  config/sync/field.storage.config_pages.su_site_403.yml
  config/sync/field.storage.config_pages.su_site_404.yml
  config/sync/field.storage.config_pages.su_site_home.yml
  config/sync/migrate_plus.migration.stanford_course_depts.yml
  config/sync/migrate_plus.migration.stanford_courses.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/views.view.stanford_courses.yml
  config/sync/views.view.taxonomy_term_pages.yml
  soe_profile.info.yml
  soe_profile.services.yml
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterLockupCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
Labels: size/xl, patch

#252 8.4.3
  CHANGELOG.md
  composer.json
  config/sync/views.view.stanford_courses.yml
  soe_profile.info.yml
Labels: size/xs, patch

#260 Updates from stanford_profile
  .circleci/config.yml
  CHANGELOG.md
  config/sync/filter.format.stanford_html.yml
  config/sync/migrate_plus.migration.stanford_course_depts.yml
  config/sync/migrate_plus.migration.stanford_courses.yml
  config/sync/oembed_providers.provider.sul_embed_service.yml
  config/sync/views.view.content.yml
  modules/stanford_date_formats/stanford_date_formats.info.yml
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.info.yml
  modules/stanford_events/modules/stanford_events_series/stanford_events_series.info.yml
  modules/stanford_events/stanford_events.info.yml
  modules/stanford_image_styles/modules/stanford_image_styles_preview/stanford_image_styles_preview.info.yml
  modules/stanford_image_styles/stanford_image_styles.info.yml
  modules/stanford_text_editor/stanford_text_editor.info.yml
  soe_profile.info.yml
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/functional/Paragraphs/GalleryCest.php
  themes/minimally_branded_subtheme/minimally_branded_subtheme.info.yml
  themes/stanford_basic/stanford_basic.info.yml
Labels: size/xs, patch

#261 D8CORE-4348 Setup Gitpod
  .gitpod.yml
  README.md
Labels: size/xs, patch
