Repository SU-SOE/soe_profile, pull requests merged in 2023-07, with the labels that each got.

#298 D8CORE-6792: fix to the CTA image hovers
  themes/soe_basic/dist/css/theme.css
  themes/soe_basic/src/scss/theme/_image-cta.scss
Labels: size/s

#299 10.0.1
  CHANGELOG.md
  config/sync/field.field.node.stanford_event.su_event_components.yml
  config/sync/field.field.node.stanford_event_series.su_event_series_components.yml
  config/sync/field.field.node.stanford_news.su_news_components.yml
  config/sync/field.field.node.stanford_person.su_person_components.yml
  config/sync/field.field.node.stanford_publication.su_publication_components.yml
  soe_profile.info.yml
  themes/minimally_branded_subtheme/dist/css/minimally_branded_subtheme.css
  themes/minimally_branded_subtheme/dist/js/scripts.js.map
  themes/minimally_branded_subtheme/src/scss/theme/_link.scss
  themes/soe_basic/dist/css/theme.css
  themes/soe_basic/src/scss/theme/_image-cta.scss
  themes/stanford_basic/stanford_basic.theme
Labels: size/s, patch

#300 10.0.2
  .github/workflows/tests.yml
  CHANGELOG.md
  composer.json
  config/sync/chosen.settings.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/field.field.node.stanford_page.su_page_components.yml
  config/sync/google_tag.settings.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.user--user.yml
  config/sync/node.type.stanford_policy.yml
  config/sync/user.role.site_manager.yml
  config/sync/xmlsitemap.settings.node.stanford_policy.yml
  config/sync/xmlsitemap.settings.yml
  soe_profile.info.yml
  soe_profile.install
  soe_profile.post_update.php
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Contrib/NodeRevisionDeleteCest.php
  tests/codeception/acceptance/SystemCest.php
  themes/stanford_basic/decoupled-menu/.nvmrc
  themes/stanford_basic/decoupled-menu/dist/islands/main-menu.island.umd.js
  themes/stanford_basic/decoupled-menu/src/main-menu.island.tsx
  themes/stanford_basic/decoupled-menu/yarn.lock
Labels: size/l, patch
