Repository SU-SOE/soe_profile, pull requests merged in 2025-06, with the labels that each got.

#324 SOEOPS-586 | remove padding top for explore more button on stories card
  modules/soe_paragraphs/dist/css/stories-paragraph.styles.css
  modules/soe_paragraphs/lib/scss/components/stories/_stories.scss
Labels: size/xs

#323 SOEOPS-561: Fixing CSS import order.
  themes/soe_basic/dist/css/base.css
  themes/soe_basic/dist/css/theme.css
  themes/soe_basic/soe_basic.info.yml
  themes/soe_basic/soe_basic.libraries.yml
  themes/soe_basic/src/scss/base/typography/_headings.scss
  themes/soe_basic/src/scss/theme/_background-classes.scss
Labels: size/xs, patch

#325 SOEOPS-635 SOEOPS-636 | adjust stats font weight and colors
  config/sync/core.entity_form_display.paragraph.stanford_stat_card.default.yml
  themes/soe_basic/dist/css/components.css
  themes/soe_basic/dist/css/theme.css
  themes/soe_basic/src/scss/components/index.scss
  themes/soe_basic/src/scss/components/stat_card/index.scss
  themes/soe_basic/src/scss/components/stat_card/stat_card.scss
  themes/soe_basic/src/scss/utilities/variables/_colors.scss
Labels: size/s, size/xs
