Repository SU-SOE/soe_profile, pull requests merged in 2025-08, with the labels that each got.

#339 SOEOPS-685 | add specificity for footer link style
  themes/soe_basic/dist/css/base.css
  themes/soe_basic/src/scss/base/_footer.scss
Labels: size/xs

#340 SOEOPS-667 | adjust margin bottom to accommodate mobile stacking
  themes/soe_basic/dist/css/theme.css
  themes/soe_basic/src/scss/theme/_news.scss
Labels: size/xs

#343 SOEOPS-696 SOEOPS-697 | update image banner text widths
  themes/soe_basic/dist/css/theme.css
  themes/soe_basic/src/scss/theme/_hero-banner.scss
Labels: size/xs, patch

#345 12.0.0
  config/sync/block.block.soe_basic_pagetitle.yml
Labels: size/xs, major
